/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002114",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "tertiary-container": "#98a3ba",
        "on-primary": "#003824",
        "on-primary-fixed-variant": "#005236",
        "primary-fixed-dim": "#4edea3",
        "on-surface-variant": "#bbcabf",
        "tertiary-fixed": "#d8e3fb",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "surface-tint": "#4edea3",
        "on-primary-fixed": "#002113",
        "tertiary": "#bcc7de",
        "surface-container-high": "#222a3d",
        "on-tertiary-container": "#2e394c",
        "background": "#0b1326",
        "primary-fixed": "#6ffbbe",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "outline": "#86948a",
        "surface-variant": "#2d3449",
        "on-error": "#690005",
        "surface-container": "#171f33",
        "surface-container-lowest": "#060e20",
        "secondary-fixed": "#85f8c4",
        "on-primary-container": "#00422b",
        "secondary-fixed-dim": "#68dba9",
        "inverse-surface": "#dae2fd",
        "secondary": "#68dba9",
        "on-tertiary": "#263143",
        "on-tertiary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#005137",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-secondary": "#003825",
        "on-error-container": "#ffdad6",
        "on-surface": "#dae2fd",
        "on-secondary-container": "#00311f",
        "surface": "#0b1326",
        "inverse-primary": "#006c49",
        "outline-variant": "#3c4a42",
        "tertiary-fixed-dim": "#bcc7de",
        "primary-container": "#10b981",
        "primary": "#4edea3",
        "surface-dim": "#0b1326",
        "secondary-container": "#25a475",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
