"""Checkpoint 4 / 4.5 orchestrator: coordinate-collision status, historical
event dates, target quality tiers, chronology, forecast-origin ledger,
source snapshots, forecast targets, walk-forward fold candidates, and
dataset-freeze metadata — all generated reproducibly from Checkpoint
2.5's conservative canonical dataset (never from raw source files
directly, and never mutating them).

Run locally (never in CI — local_data/ is gitignored and not present in
the repo, same convention as build_canonical.py):

    cd backend
    python -m components.geospatial_tracking.services.build_historical_replay \
        ../local_data/pistes_raw ../local_data/processed/canonical_outbreaks_conservative.csv \
        ../local_data/manifests/model_candidate_report.csv ../local_data/manifests 14

Writes:
    <manifest_dir>/canonical_spatial_independence.csv  (Checkpoint 4, SUPERSEDED — kept for provenance, see below)
    <manifest_dir>/coordinate_collision_report.csv     (Checkpoint 4.5 Part 1-3 — authoritative going forward)
    <manifest_dir>/target_quality_report.csv           (Checkpoint 4, SUPERSEDED — NOT regenerated by this version)
    <manifest_dir>/target_quality_report_v2.csv         (Checkpoint 4.5 Part 5 — authoritative going forward)
    <manifest_dir>/historical_chronology.csv
    <manifest_dir>/historical_forecast_origins.csv      (includes the Part-7 source snapshot columns)
    <manifest_dir>/historical_forecast_targets.csv
    <manifest_dir>/walk_forward_fold_candidates.csv     (Checkpoint 4.5 Part 13)
    <manifest_dir>/dataset_freeze_manifest.json

METHODOLOGICAL HISTORY, NOT SILENTLY OVERWRITTEN (master-prompt Part 15):
`canonical_spatial_independence.csv` used a misleadingly-named boolean
(coordinate uniqueness called "spatial independence" — see
`services/coordinate_collision.py`'s module docstring for exactly why
that overstated the evidence). This orchestrator still generates it
(unchanged code, `services/canonical_spatial.py`), so a prior run's file
on disk is reproducible and comparable, but `coordinate_collision_report.csv`
is the corrected, authoritative artifact from Checkpoint 4.5 onward.
Likewise `target_quality_report.csv`'s old boolean-based schema is no
longer regenerated by this version of the orchestrator — the file may
still exist on disk from a Checkpoint 4 run for comparison, but
`target_quality_report_v2.csv` (STRICT/RESOLVED_ONLY tier variants) is
authoritative going forward.

`active_window_days` (the 5th CLI arg) is an EXPLICIT UNFROZEN_DEVELOPMENT_PARAMETER
— never claimed scientifically correct, see config.py / REPOSITORY_DESIGN.md.

COUNTRY_SCOPE NOTE (master-prompt Checkpoint 4.5 Part 9): every
per-country breakdown this script produces (chronology, origins, folds) is
a SURVEILLANCE/DATA-REPLAY BOUNDARY for how this corpus happens to be
organized — never a claim that disease transmission stops at a national
border. No cross-border epidemiological modeling exists in this
checkpoint or anywhere in this component yet.
"""

from __future__ import annotations

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

from ..config import DEFAULT_SQLITE_DB_PATH
from ..repositories.sqlite_repository import SQLiteOutbreakRepository
from .canonical_spatial import compute_canonical_spatial_independence
from .canonical_spatial import load_conservative_rows as load_conservative_rows_legacy
from .coordinate_collision import compute_coordinate_collision_status, load_conservative_rows
from .dataset_freeze import write_dataset_freeze_manifest
from .dates import parse_flexible_date
from .disease import DEFAULT_DISEASE
from .forecast_origin import build_forecast_origin_ledger, build_source_snapshot
from .forecast_target import build_forecast_targets
from .historical_event_date import derive_historical_event_date
from .historical_import import import_conservative_csv
from .target_quality import compute_target_quality_tiers
from .walk_forward import build_candidate_folds, propose_chronological_boundaries

DISEASE = DEFAULT_DISEASE
"""FMD-02: backward-compatible alias. The single canonical source of truth
for the default disease is now `services.disease.DEFAULT_DISEASE`; this
name is kept, unchanged in value, because ~20 existing modules/tests
(api/router.py, services/application/frozen_geospatial_analysis_10a.py,
smoke_tests/, tests/test_checkpoint_10a_runtime_api.py, and others) import
`DISEASE` from this module directly. Nothing about this alias changes
`run()`'s default behavior below."""


def _write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def run(
    raw_dir: str,
    conservative_csv_path: str,
    model_candidate_report_path: str,
    manifest_dir: str,
    active_window_days: int,
    *,
    disease: str = DISEASE,
) -> dict:
    """FMD-02: `disease` is now an explicit keyword-only parameter --
    defaults to the module's `DISEASE` constant (== `DEFAULT_DISEASE` ==
    "Lumpy skin disease"), so every existing positional call site (the
    CLI entry point below, any script/test calling `run(...)` with five
    positional args) reproduces the exact pre-FMD-02 LSD-only replay
    unchanged. Passing a different disease replays history for that
    disease's own corpus instead -- it does NOT change which frozen
    scientific parameters (kernel/rate) a later runtime analysis would
    use; this orchestrator never touches those."""
    manifest_path = Path(manifest_dir)
    repo_root = Path(__file__).resolve().parents[4]  # .../backend/components/geospatial_tracking/services -> repo root

    # -- coordinate-collision status (Checkpoint 4.5 Parts 1-3), authoritative --
    conservative_rows = load_conservative_rows(conservative_csv_path)
    collision_results = compute_coordinate_collision_status(conservative_rows)
    collision_by_id = {r.source_record_id: r.coordinate_collision_status for r in collision_results}
    _write_csv(
        manifest_path / "coordinate_collision_report.csv",
        [r.as_dict() for r in collision_results],
        ["source_record_id", "latitude", "longitude", "gps_quality", "dedup_status",
         "coordinate_collision_status", "shared_coordinate_group_id",
         "resolved_shared_count", "unresolved_shared_count", "reason"],
    )

    # -- legacy canonical_spatial_independence.csv (Checkpoint 4, superseded, kept for provenance) --
    legacy_rows = load_conservative_rows_legacy(conservative_csv_path)
    legacy_results = compute_canonical_spatial_independence(legacy_rows)
    _write_csv(
        manifest_path / "canonical_spatial_independence.csv",
        [r.as_dict() for r in legacy_results],
        ["source_record_id", "latitude", "longitude", "gps_quality", "dedup_status",
         "canonical_spatial_independence", "shared_coordinate_group_id", "shared_coordinate_count", "reason"],
    )

    # -- fresh dev DB, seeded from the conservative CSV (full corpus, unfiltered) --
    db_path = Path(__file__).resolve().parents[1] / DEFAULT_SQLITE_DB_PATH
    if db_path.exists():
        db_path.unlink()
    repo = SQLiteOutbreakRepository(db_path)
    repo.init_schema()
    imported_count = import_conservative_csv(repo, conservative_csv_path)

    # -- target quality tiers v2 (Checkpoint 4.5 Part 5) + historical event dates --
    all_records = repo.list_historical_records()
    quality_rows = []
    for record in all_records:
        collision_status = collision_by_id.get(record.source_record_id, "UNKNOWN")
        tiers = compute_target_quality_tiers(record, coordinate_collision_status=collision_status)
        quality_rows.append(tiers.as_dict())
    _write_csv(
        manifest_path / "target_quality_report_v2.csv",
        quality_rows,
        ["source_record_id", "risk_target_eligible", "direction_target_tier_a_strict",
         "direction_target_tier_a_resolved_only", "direction_target_tier_b",
         "speed_target_tier_a_strict", "speed_target_tier_a_resolved_only", "speed_target_tier_b",
         "speed_eligibility_status", "historical_event_date", "historical_event_date_quality",
         "coordinate_collision_status", "reason"],
    )

    # -- chronology audit (Part 5) — dedup-resolved model candidates only -------
    from ..schemas import DEDUP_RESOLVED_STATUSES

    candidates = [r for r in all_records if r.model_candidate and r.dedup_status in DEDUP_RESOLVED_STATUSES]
    chronology_rows = []
    by_country: dict[str, list] = defaultdict(list)
    for record in candidates:
        event = derive_historical_event_date(record)
        by_country[record.country or "UNKNOWN"].append((record, event))

    for country, entries in sorted(by_country.items()):
        dated = [(r, e) for r, e in entries if e.historical_event_date]
        # Parse before sorting/bucketing — historical_event_date strings mix
        # "YYYY-MM-DD" (CSV) and "YYYY/MM/DD" (WAHIS) formats. Naive string
        # sorting is WRONG here: within the same year, "-" (0x2D) sorts
        # before "/" (0x2F) regardless of the actual month/day, so a later
        # WAHIS date in a given year could sort before an earlier CSV date
        # in that same year. Always parse to real `date` objects first.
        parsed_dates = sorted(d for d in (parse_flexible_date(e.historical_event_date) for _, e in dated) if d)
        source_systems = Counter(r.source_record_id.split(":", 1)[0] for r, _ in entries)
        gps_qualities = Counter(r.gps_quality for r, _ in entries)
        collision_counts = Counter(collision_by_id.get(r.source_record_id, "UNKNOWN") for r, _ in entries)
        monthly_counts = Counter(d.strftime("%Y-%m") for d in parsed_dates)
        chronology_rows.append(
            {
                "country": country,
                "candidate_count": len(entries),
                "records_with_usable_event_date": len(dated),
                "unique_event_dates": len({d.isoformat() for d in parsed_dates}),
                "event_date_range_start": parsed_dates[0].isoformat() if parsed_dates else "",
                "event_date_range_end": parsed_dates[-1].isoformat() if parsed_dates else "",
                "gps_quality_counts": json.dumps(dict(gps_qualities)),
                "coordinate_collision_status_counts": json.dumps(dict(collision_counts)),
                "source_system_counts": json.dumps(dict(source_systems)),
                "monthly_counts": json.dumps(dict(sorted(monthly_counts.items()))),
            }
        )
    _write_csv(
        manifest_path / "historical_chronology.csv",
        chronology_rows,
        ["country", "candidate_count", "records_with_usable_event_date", "unique_event_dates",
         "event_date_range_start", "event_date_range_end", "gps_quality_counts",
         "coordinate_collision_status_counts", "source_system_counts", "monthly_counts"],
    )

    # -- forecast-origin ledger + source snapshot (Parts 6-7) --------------------
    origins = build_forecast_origin_ledger(repo, disease=disease)
    origin_rows = []
    all_targets = []
    targets_by_origin_id: dict[str, list] = {}
    origins_with_target = 0
    origins_with_zero_source = 0
    origins_with_zero_target = 0
    target_event_id_counter: Counter[str] = Counter()

    for origin in origins:
        snapshot = build_source_snapshot(repo, origin, disease=disease, active_window_days=active_window_days)
        row = origin.as_dict()
        row.update(
            {
                "source_ids": snapshot.source_ids and ";".join(snapshot.source_ids) or "",
                "source_count": snapshot.source_count,
                "source_effective_dates": ";".join(snapshot.source_effective_dates),
                "source_availability_quality": ";".join(snapshot.source_availability_quality),
                "active_window_days": snapshot.active_window_days,
                "active_window_days_label": snapshot.active_window_days_label,
            }
        )
        origin_rows.append(row)
        if snapshot.source_count == 0:
            origins_with_zero_source += 1

        targets = build_forecast_targets(
            repo,
            origin,
            disease=disease,
            source_ids_at_origin=set(snapshot.source_ids),
            coordinate_collision_status_by_id=collision_by_id,
        )
        targets_by_origin_id[origin.forecast_origin_id] = targets
        if targets:
            origins_with_target += 1
        else:
            origins_with_zero_target += 1
        for t in targets:
            target_event_id_counter[t.target_event_id] += 1
        all_targets.extend(targets)

    _write_csv(
        manifest_path / "historical_forecast_origins.csv",
        origin_rows,
        ["forecast_origin_id", "country", "t0", "temporal_mode", "trigger_source_ids_at_t0",
         "trigger_source_count", "source_ids", "source_count", "source_effective_dates",
         "source_availability_quality", "active_window_days", "active_window_days_label"],
    )
    _write_csv(
        manifest_path / "historical_forecast_targets.csv",
        [t.as_dict() for t in all_targets],
        ["forecast_origin_id", "target_id", "target_event_id", "historical_event_date", "lead_days",
         "latitude", "longitude", "gps_quality", "coordinate_collision_status", "risk_target_eligible",
         "direction_target_tier_a_strict", "direction_target_tier_a_resolved_only", "direction_target_tier_b",
         "speed_target_tier_a_strict", "speed_target_tier_a_resolved_only", "speed_target_tier_b",
         "speed_eligibility_status", "country", "disease", "dedup_status", "model_candidate"],
    )

    # -- candidate walk-forward folds (Checkpoint 4.5 Part 13) -------------------
    fold_rows: list[dict] = []
    num_folds = 5
    try:
        boundaries = propose_chronological_boundaries(origins, num_folds=num_folds)
        folds = build_candidate_folds(origins, targets_by_origin_id, boundaries=boundaries)
        fold_rows = [f.as_dict() for f in folds]
    except ValueError:
        folds = []
    _write_csv(
        manifest_path / "walk_forward_fold_candidates.csv",
        fold_rows,
        ["fold_id", "training_date_range_end", "validation_date_range_start", "validation_date_range_end",
         "purged_origin_count", "training_origin_count", "validation_origin_count",
         "unique_validation_target_events", "risk_eligible_validation_targets",
         "strict_tier_a_direction_validation_targets", "countries_represented"],
    )

    # Thailand-only direction fold schedule (SPLIT_PROTOCOL_DRAFT.md Part 11 —
    # Thailand dominates Tier-A depth, so a separate schedule is proposed
    # alongside the global one, never replacing it).
    thailand_origins = [o for o in origins if o.country == "Thailand"]
    thailand_fold_rows: list[dict] = []
    try:
        th_boundaries = propose_chronological_boundaries(thailand_origins, num_folds=num_folds)
        th_folds = build_candidate_folds(
            thailand_origins, targets_by_origin_id, boundaries=th_boundaries, fold_id_prefix="THAILAND_FOLD"
        )
        thailand_fold_rows = [f.as_dict() for f in th_folds]
    except ValueError:
        pass
    _write_csv(
        manifest_path / "walk_forward_fold_candidates_thailand_direction.csv",
        thailand_fold_rows,
        ["fold_id", "training_date_range_end", "validation_date_range_start", "validation_date_range_end",
         "purged_origin_count", "training_origin_count", "validation_origin_count",
         "unique_validation_target_events", "risk_eligible_validation_targets",
         "strict_tier_a_direction_validation_targets", "countries_represented"],
    )

    # -- dataset freeze manifest (Part 15) ---------------------------------------
    freeze_manifest = write_dataset_freeze_manifest(
        manifest_path / "dataset_freeze_manifest.json",
        raw_dir=raw_dir,
        conservative_csv_path=conservative_csv_path,
        model_candidate_report_path=model_candidate_report_path,
        repo_root=repo_root,
    )

    repo.close()

    repeated_targets = {k: v for k, v in target_event_id_counter.items() if v > 1}

    return {
        "imported_historical_records": imported_count,
        "coordinate_collision_status_counts": dict(
            Counter(r.coordinate_collision_status for r in collision_results)
        ),
        "quality_tier_counts": {
            "risk_target_eligible": sum(1 for r in quality_rows if r["risk_target_eligible"]),
            "direction_target_tier_a_strict": sum(1 for r in quality_rows if r["direction_target_tier_a_strict"]),
            "direction_target_tier_a_resolved_only": sum(
                1 for r in quality_rows if r["direction_target_tier_a_resolved_only"]
            ),
            "direction_target_tier_b": sum(1 for r in quality_rows if r["direction_target_tier_b"]),
        },
        "chronology_countries": len(chronology_rows),
        "forecast_origin_count": len(origins),
        "origins_with_at_least_one_target": origins_with_target,
        "origins_with_zero_source": origins_with_zero_source,
        "origins_with_zero_target": origins_with_zero_target,
        "unique_target_events": len(target_event_id_counter),
        "total_target_rows": len(all_targets),
        "repeated_target_event_appearances": len(repeated_targets),
        "max_repeats_for_one_target_event": max(target_event_id_counter.values()) if target_event_id_counter else 0,
        "global_fold_count": len(fold_rows),
        "thailand_fold_count": len(thailand_fold_rows),
        "dataset_freeze_manifest": freeze_manifest,
    }


def print_summary(stats: dict) -> None:
    print(f"imported historical records: {stats['imported_historical_records']}")
    print(f"coordinate collision status counts: {stats['coordinate_collision_status_counts']}")
    print(f"target quality tier counts: {stats['quality_tier_counts']}")
    print(f"chronology countries: {stats['chronology_countries']}")
    print(f"forecast origins: {stats['forecast_origin_count']}")
    print(f"  origins with >=1 D1-D7 target: {stats['origins_with_at_least_one_target']}")
    print(f"  origins with zero source: {stats['origins_with_zero_source']}")
    print(f"  origins with zero target: {stats['origins_with_zero_target']}")
    print(f"unique target events: {stats['unique_target_events']}")
    print(f"total target rows (across all origins): {stats['total_target_rows']}")
    print(f"target events repeated across >1 origin: {stats['repeated_target_event_appearances']}")
    print(f"max repeats for one target event: {stats['max_repeats_for_one_target_event']}")
    print(f"global candidate folds: {stats['global_fold_count']}")
    print(f"Thailand-only direction candidate folds: {stats['thailand_fold_count']}")
    print(f"dataset freeze git_commit: {stats['dataset_freeze_manifest']['git_commit']}")


if __name__ == "__main__":
    args = sys.argv[1:]
    raw_dir = args[0] if len(args) > 0 else "../local_data/pistes_raw"
    conservative_csv_path = args[1] if len(args) > 1 else "../local_data/processed/canonical_outbreaks_conservative.csv"
    model_candidate_report_path = args[2] if len(args) > 2 else "../local_data/manifests/model_candidate_report.csv"
    manifest_dir = args[3] if len(args) > 3 else "../local_data/manifests"
    active_window_days = int(args[4]) if len(args) > 4 else 14
    stats = run(raw_dir, conservative_csv_path, model_candidate_report_path, manifest_dir, active_window_days)
    print_summary(stats)
