from pydantic import BaseModel
from typing import List, Dict, Optional


class Detection(BaseModel):
    bbox: List[float]
    confidence: float
    class_name: str


class BoundingBoxNormalized(BaseModel):
    x1: float
    y1: float
    x2: float
    y2: float


class BestDetection(BaseModel):
    bbox: List[float]
    confidence: float
    bbox_normalized: BoundingBoxNormalized


class Disease(BaseModel):
    name: str
    confidence: float
    all_probabilities: Dict[str, float]


class SeverityMetrics(BaseModel):
    score: Optional[float] = 0.0
    grade: str  # e.g. "Severe" | "Moderate" | "Mild" | "None" | "Healthy Baseline"
    description: Optional[str] = None  # Comprehensive clinical severity narrative generated by LLM
    prognosis: Optional[str] = None  # Clinical prognosis
    diagnostic_rationale: Optional[str] = None  # Dynamic diagnostic rationale from LLM reasoning
    spatial_correlation: Optional[str] = None  # Dynamic image-specific anatomical spatial correlation
    lesion_coverage_pct: float = 0.0
    cluster_count: int = 0
    mean_intensity: float = 0.0
    formatted: Optional[str] = None  # e.g. "Severe"
    source: Optional[str] = "llm_reasoning"  # "llm_reasoning" | "vision_telemetry" | "composite_scoring"
    confidence_level: Optional[str] = "High"  # "High" | "Moderate" | "Low"
    needs_review: bool = False
    attention_coverage_pct: float = 0.0
    attention_cluster_count: int = 0
    top2_margin: Optional[float] = None
    composite_score: Optional[float] = None


class DetectResponse(BaseModel):
    cattle_detected: bool
    detections: List[Detection]
    best_detection: Optional[BestDetection]
    disease: Optional[Disease]
    severity: Optional[SeverityMetrics] = None
    spatial_correlation: Optional[str] = None
    cropped_image: Optional[str]
    symptoms_image: Optional[str] = None
    image_size: Optional[Dict[str, int]]
    device: Optional[str]


# ---------------------------------------------------------------------------
# Tier 3 — LLM Clinical Reasoning
# ---------------------------------------------------------------------------

class ReasoningRequest(BaseModel):
    """Request body for POST /api/reason.

    Accepts the full detection result from /api/detect plus optional
    farm metadata for richer LLM context.
    """
    cattle_detected: bool
    detections: List[Detection]
    best_detection: Optional[BestDetection] = None
    disease: Optional[Disease] = None
    severity: Optional[SeverityMetrics] = None
    spatial_correlation: Optional[str] = None
    image_size: Optional[Dict[str, int]] = None
    farm_metadata: Optional[Dict[str, str]] = None


class ReasoningResponse(BaseModel):
    """Response body for POST /api/reason."""
    status: str                  # "ok" | "error"
    reasoning_report: str        # Markdown clinical briefing (or error message)
    model_name: Optional[str] = None  # LLM model that produced the report
    severity_assessment: Optional[SeverityMetrics] = None  # Parsed dynamic LLM clinical severity

